apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep-new
  labels:
    app: webserver     
spec:
  selector:
    matchLabels:      
      app: webserver        
  replicas: 3
  template:
    metadata:
      labels: 
        app: webserver     
    spec:
      containers:
      - name: nginx
        image: nginx:latest
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: app
               operator: In
               values: 
               - vikas
      tolerations:
      - key: app
        operator: Equal
        value: frontend
        effect: NoExecute          

