apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
  labels:
    app: webserver     
spec:
  selector:
    matchLabels:      
      app: webserver        
  replicas: 3
  template:
    metadata:
      labels: 
        app: webserver     
    spec:
      containers:
      - name: nginx
        image: nginx:latest
      nodeSelector:
        app: webserver


