apiVersion: v1
kind: Pod
metadata:
  name: nginx-2      
  labels:
    app: webserver      
spec:
  containers:
  - image: nginx:latest
    name: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "400Mi"
        cpu: "400m"
