apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rpctlr
  labels:
    app: webserver
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx
        image: nginx:latest
